[[constraint]]
  name = "github.com/google/go-github"
  version = "^21.0.0"

[[constraint]]
    name = "github.com/Azure/brigade"
    version = "^0.20.0"

[[constraint]]
  name = "github.com/gosuri/uitable"
  branch = "master"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "^1.3.1"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "gopkg.in/gin-gonic/gin.v1"
  version = "1.2.0"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"
